### ISSUE TITLE
3D pinch interaction and grab object interactions do not work

### ISSUE THREAD

**Issue by cpinter** [KitwareMedical/SlicerVirtualReality#102]
* Build the latest Slicer 5.3.0 with the latest SlicerVR
* Copy the manifest json files into the folder of Slicer.exe
* Start VR
* I used an HP Reverb 2 headset

None of the interactions worked, including flying, grab&move objects, and 3D pinch. The latter two at least worked a few months ago. Maybe some of the latest commits in VTK or here broke them?

I updated OpenVR to the latest version and tried the same Slicer 5.3.0 + SlicerVR on another computer with HTC Vive Pro but there was no change.

**Comment by cpinter** [comment]
This is due to the `RecognizeComplexGesture` function being commented out since https://github.com/KitwareMedical/SlicerVirtualReality/commit/1c36e4031f32e0cd552c5ef027cf5be420fbc5e1

**Comment by cpinter** [comment]
The problem is that getting the controller physical pose matrices return identity matrix ([here](https://github.com/KitwareMedical/SlicerVirtualReality/blob/master/VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.cxx#LL795C2-L795C2)). Otherwise I think it should work so we only need to find how to get those poses. @LucasGandel do you have any off-hand idea by any chance? Maybe after the API change it is retrieved another way? Thanks!

**Comment by jcfr** [comment]
Related to `RecognizeComplexGesture`:

* [MR-9892 | ENH: Re-introduce support for custom logic handling VR complex gesture](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9892) will be integrated into upstream VTK.

* In the meantime, worth noting that:
  * All commits from `MR-9892` have been added to the updated VTK being integrated through:
    * https://github.com/Slicer/Slicer/pull/7010
  * The first commit of `MR-9892` titled `Re-introduce support for custom logic handling VR complex gesture` is already in the current version of [Slicer/VTK@slicer-v9.1.20220125-efbe2afc2](https://github.com/Slicer/VTK/commits/slicer-v9.1.20220125-efbe2afc2) as https://github.com/Slicer/VTK/commit/6efd97c519d0cb813a31e52c232161e73b64a7e8 

> None of the interactions worked, including flying, grab&move objects, and 3D pinch
> 

Indeed, see:
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/91

> how to get those poses

In the context of `OpenVR`, corresponding API has been re-introduced in `Slicer/VTK`. Relevant commit titles are:

| Title | `slicer-v9.1.20220125-efbe2afc2` | `slicer-v9.2.20230607-1ff325c54` | 
|--|--|--|
| `ENH: Re-introduce OpenVR API for retrieving last OpenVR pose` | https://github.com/Slicer/VTK/commit/c3337503833f2392f42a2f8af0461fffcdd0c94c | https://github.com/Slicer/VTK/commit/c6189a4a27138bd6d0df709f5c4fd28b3801ccb9 |
| `BUG: Ensure a valid OpenVR pose is returned` | https://github.com/Slicer/VTK/commit/b74591f27e11bb7d8f750fd96ae85fa48cf67e63 | https://github.com/Slicer/VTK/commit/0227875f009ce4d7632b43ca84e5552ed6d3c753 |

Since this approach is specific to `RenderingOpenVR`, I suggest we work with @LucasGandel to come with an approach that would also work with `RenderingOpenXR`.

**Comment by cpinter** [comment]
Thanks @jcfr !

I updated the hash in an attempt to use the new SlicerVTK branch, and got these error messages when building

```
    vtkMeshQuality.cxx

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1290,10): error C2653: 'verdict': is not a class or namespace name [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1290,19): error C3861: 'tri_area': identifier not found [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1303,10): error C2653: 'verdict': is not a class or namespace name [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1303,19): error C3861: 'tri_edge_ratio': identifier not found [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1316,10): error C2653: 'verdict': is not a class or namespace name [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1316,19): error C3861: 'tri_aspect_ratio': identifier not found [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1329,10): error C2653: 'verdict': is not a class or namespace name [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1329,19): error C3861: 'tri_radius_ratio': identifier not found [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1342,10): error C2653: 'verdict': is not a class or namespace name [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1342,19): error C3861: 'tri_aspect_frobenius': identifier not found [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1355,10): error C2653: 'verdict': is not a class or namespace name [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]

C:\d\S5R\VTK\Filters\Verdict\vtkMeshQuality.cxx(1355,19): error C3861: 'tri_minimum_angle': identifier not found [C:\d\S5R\VTK-build\Filters\Verdict\FiltersVerdict-objects.vcxproj] [C:\d\S5R\VTK.vcxproj]
...
```
(and a lot of the same)

For now I'll just try to fix the relevant part in vtkOpenVRRenderWindow.cxx that always sets the pose to null, but I thought this would be good to know.

**Comment by LucasGandel** [comment]
@cpinter The verdict related issue can be fixed by removing the ThirdParty/verdict folder in your build directory and rebuilding.

Besides that, I confirm we must work on an approach that is common to both OpenXR and OpenVR and which does not expose specific OpenVR/OpenXR types in the public API.

**Comment by jcfr** [comment]
> re: Slicer + latest VTK
There are errors on the Slicer side that I am fixing.  So far, since these are located in CLIs, you should be able to comment the code.

**Comment by jcfr** [comment]
> After that, this is how I could use the interactions. I use an HP Reverb 2 headset.

Fore reference this was fixed by https://github.com/KitwareMedical/SlicerVirtualReality/commit/49f1896d652c6b27051cd41e8244b52cd28c2dab 

Thanks @cpinter for working on the fix.

@LucasGandel The current approach makes use of the `vtkOpenVRRenderWindow::GetOpenVRPose` method specific to `Slicer/VTK`[^1], I am wondering if we could generalize and have an API common to `OpenVR` and `OpenXR`.

[^1]: https://github.com/Slicer/VTK/compare/97a187572d4000cd820f9fc887f21eaf0bde857c...b74591f27e11bb7d8f750fd96ae85fa48cf67e63
