### ISSUE TITLE
Consolidate InteractorStyle integration

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerVirtualReality#123]
Currently `vtkVirtualRealityViewInteractorStyle` derives from `vtkMRMLViewInteractorStyle` so that the style can be associated with the displayable manager group[^1].

This is required to allow the Slicer VTK widgets to handle events.

This approach require to duplicate some of the code implemented in `vtkVRInteractorStyle`[^2]

## Questions

* Should some of the logic in `vtkVRInteractorStyle` be moved to static function or helper class ?

[^1]: a displayable manager group is collection of displayable managers each adding support for capability like volume rendering, markups, transform, ... in a given view.

[^2]: https://github.com/Kitware/VTK/blob/master/Rendering/VR/vtkVRInteractorStyle.cxx

**Comment by LucasGandel** [comment]
> Should some of the logic in vtkVRInteractorStyle be moved to static function or helper class ?

This sound difficult due to most of the logic being based on internal class variables. However can we consider it the other way round?
It should be possible to use vtkVRInteractorStyle directly and have a delegate class that observes the interactor style events. This delegate class should store the DisplayableManagers and be responsible for calling the dispatch event function. I am just not sure how easy the DisplayableManagers can be set on this delegate to replace how it is done currently for vtkMRMLViewInteractorStyle
