### ISSUE TITLE
Help to install and run the extension on Win PC

### ISSUE THREAD

**Issue by Jasan-CZ** [KitwareMedical/SlicerVirtualReality#165]
Dear, it seems I need to help with the "SlicerVirtualReality" extension. I have my htc vive pro 2 headset, SteamVR in version 2.2.3 is working properlly and installed Sicer 5.6.0. I assumed I would download the extension from this link (https://extensions.slicer.org/view/SlicerVirtualReality/30822/win) and install it in Extension manager in Slicer (open the zip-file and restart). But after that I can't see the Extension in Modules. Could you please help me to install it? Win 11, AMD proc.
Thanks, Jan.

![Clipboard01](https://github.com/KitwareMedical/SlicerVirtualReality/assets/35166242/ed1a136a-8e95-42f0-b9fd-5868a39c9d86)

**Comment by jcfr** [comment]
The extension is built daily for:
* latest `Stable` release. Note that this is `5.6.1` (and not `5.6.0`)
* latest `Preview` release

It means that you should be able to simply download Slicer 5.6.1 from https://download.slicer.org and install the extension.

While we do our best to backport functionality to the latest `Stable`, the most recent improvements (e.g OpenXR Remoting) will only be available with the `Preview` release.

Since for the past two days, the build failed for unrelated issue, the latest Preview build with the Virtual extension would be this one[^1]: https://download.slicer.org/?revision=32692

[^1]: The revision number was obtained by clicking the "Prev" button using a link like this one: https://slicer.cdash.org/index.php?project=SlicerPreview&date=2024-01-20&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=VirtualReality

**Comment by jcfr** [comment]
If you don't have any additional question, I will let you close the issue. :pray:

**Comment by Jasan-CZ** [comment]
If I understand correctly, I must always have the latest stable version of Slicer installed?

**Comment by lassoan** [comment]
If the Slicer version you are using works well for you then you don't have to update to the latest version (although it is still recommended because we constantly add new features and fix various issues).

If you run into any problems then of course you must update your Slicer to a more recent version that contains the fix.
