### ISSUE TITLE
Volume rendering does not show up if other data is shown

### ISSUE THREAD

**Issue by cpinter** [KitwareMedical/SlicerVirtualReality#41]
In this scene there are models, segmentations, volume slices, and a volume rendering, but the volume rendering does not show up in VR:
https://www.dropbox.com/s/idf6be25x10vobg/20180911_VR_VolumeRenderingNotShowingBug.mrb?dl=0

**Comment by cpinter** [comment]
It seems that the issue occurs with the scene above, but when constructing a new scene, it works. Need to check if it's about loading a scene with volume rendering in it.

**Comment by lassoan** [comment]
The issue is in the scene. For display node (vtkMRMLGPURayCastVolumeRenderingDisplayNode2) "ViewNodeIDs[0]: vtkMRMLViewNode1" is specified. If there are no other 3D view nodes, then on the GUI this appears as "All". However, if you add a new 3D view, the specified node ID will prevent the volume to appear on any other view (and on the GUI "All" is not replaced by "View1").

The behavior is not ideal, but I don't think we need to do anything about it in SlicerVirtualReality.
