### ISSUE TITLE
Add support for Multi-GPU processing

### ISSUE THREAD

**Issue by TreckZero** [KitwareMedical/SlicerVirtualReality#86]
I'm wondering if it's possible to get multiple GPUs working in parallel to make the load lighter when working on higher detail data sets.

**Comment by lassoan** [comment]
In theory [VR multi-GPU rendering support](https://developer.nvidia.com/blog/vr-sli-accelerating-opengl-virtual-reality-multi-gpu-rendering/) could be implemented. However, the number of systems with compatible multi-GPU configurations is so low, that it is not worth investing time into developing, testing, and maintaining this. For the same reason, game developers don't implement support for it either and so most likely this feature is not tested much and therefore the implementation in the driver and OpenVR may be quite buggy, too.

The implementation would require modification of the OpenVR implementation in VTK. VTK's OpenVR implementation is being ported to OpenXR, so even if someone would implement SLI support in the current VTK version, that would need to be reimplemented for OpenXR.

Overall, it is not yet the time to add multi-GPU support, and this year (before VTK's OpenXR based implementation is released) would be a particularly bad time. I close this issue now so that we can keep track of items in the issue tracker that we are planning to address in the foreseeable future.
