### ISSUE TITLE
Add mechanism to allow the user to rotate in the viewer

### ISSUE THREAD

**Issue by markasselin** [KitwareMedical/SlicerVirtualReality#9]
Currently the user can only rotate by turning their head - there should also be a mechanism for them to rotate the viewer independently of their head.

Perhaps we could use the grip button on the VIVE controller for this purpose, and have the rotation done by rotating the controller with the grip button pressed.

**Comment by cpinter** [comment]
Feature added in commit https://github.com/KitwareMedical/SlicerVirtualReality/commit/290beba8443b0bfa7ff86f6872a809e2fd8b5e2d

The difference between what is implemented and what @markasselin described is that instead of using one controller's grip, both controller's grip needs to be used to enter the free-form world manipulation mode. If the user holds both grip buttons, then those controller positions are stored and as the user moves the controllers the rendered world is transformed so that the controller positions correspond to the same two world positions (and orientations). Thus, panning, scaling, and rotation can be achieved at the same time.

The issue can be closed when the extension index hash is after the merge request https://gitlab.kitware.com/vtk/vtk/merge_requests/4726 is integrated, and VTK in Slicer updated to include that commit.
